version: "3"
services:
  truthtables:
    build: https://github.com/cs481-ekh/s22-truth-tables.git#MigrateToBsu-55
    image: truthtables
    ports:
      - "8080:8080"
    networks:
      - truthtables-mysql
    depends_on:
      - mysqldb
    volumes:
      - test:/test

  mysqldb:
    image: mysql:8
    networks:
      - truthtables-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=truthtables
    volumes:
      - .:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
      - test:/docker-entrypoint-initdb.d
volumes:
  data:
  test:
networks:
  truthtables-mysql: